device: "cpu"  # Use "cuda" for GPU, "mps" for Mac, or "cpu" #for keypoint matching acceleration
image_directory: "C:\\Users\\kazuy\\Documents\\GEMINI\\Panorama\\08_28_2024_B5_frames_10fps" #stitches all files in image_directory assuming they are already in stitching order
output_dir: "C:\\Users\\kazuy\\Documents\\GEMINI\\Panorama\\output"
output_filename: "batch_08_28_2024_B5.png"
feature_resolution: 0.3 #reduce resolution of original images by this factor for feature extraction
final_resolution: 0.3 #reduce resolution of original images by this factor for final panorama, 1 for native resolution
seam_resolution: 0.5 #reduce resolution of final resolution by this amount to find seams and for cropping
stitching_direction: "LEFT" #("RIGHT", "UP", "DOWN") which edge of image is stitched to the next image
keypoint_prop: 0.5 #starting range to filter for how close the keypoints need to be to stitching edge, 1.0 to turn off, default 0.5 should by multiple of 0.1
forward_limit: 5 #number of images ahead that can be stitched
xy_ratio: 1.2 #minimum direction of travel/normal direction of travel in homography
scale_constraint: 0.25 #maximum value that abs(scale-1) can take in homography
min_inliers: 20 #the minimum number of inlier matches necessary to consider it a match, 20-50, should increase with max_reprojection_error
max_RANSAC_thresh: 3 #maximum threshold for RANSAC to try to get min_inliers, 1-5, should increase with image noise
refine: True #tries to exclude the worst keypoint matches based on LMEDS reprojection error
max_reprojection_error: 15.0 #number of pixels of reprojection error that the homography inliers can have to be considered a good match, 10-25
camera: "spherical" #"spherical", "partial affine"
batch_size: 10 #batch size over 50 will lead to long bundle adjustment, 20 is recommended
crop: True #used on the final panorama, only works if the final panorama is relatively straight
