device: "cuda"  # Use "cuda" for GPU, "mps" for Mac, or "cpu"
image_directory: "../data/camB_smallest_subset/"
save_image: True
output_dir: "../output"
output_filename: "camB_smallest_subset_ransac.png"
batch_size: 50
max_workers: 8
left_crop: 300
right_crop: 300
top_crop: 50
bottom_crop: 50
fixed_height: 768
fixed_width: 1024
extractor: 'superpoint'
H_transform_method: 'RANSAC' # 'LMEDS'