device: "cuda"  # Use "cuda" for GPU, "mps" for Mac, or "cpu"
image_directory: "../data/kramlich-subset/rgb"
depth_directory: "../data/kramlich-subset/depth"
save_image: True
output_dir: "../output"
output_filename: "grape_xtrans_expdecay.png"
batch_size: 50
max_workers: 8
left_crop: 0
right_crop: 0
top_crop: 0
bottom_crop: 50
fixed_height: 768
fixed_width: 1024
extractor: 'superpoint'
H_transform_method: 'RANSAC' # 'LMEDS'
pts_transformation: 'translation_x' # 'translation_x', 'translation_y', 'translation_2d', 'translation_scale', 'rotation_translation', 'affine_partial', 'affine_full'